services:
  app:
    container_name: v2-app
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    volumes:
      - .:/var/www/html
      - /Volumes/Third/Users/zbyszek/kerichogold:/var/www/kerichogold
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - v2-network
    depends_on:
      - db
      - redis

  queue:
    container_name: v2-queue
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    networks:
      - v2-network
    depends_on:
      - db
      - redis
      - app

  redis:
    image: redis:alpine
    container_name: v2-redis
    networks:
      - v2-network
    ports:
      - "6380:6379"

  web:
    container_name: v2-web
    image: nginx:alpine
    # Ports 80 and 443 will be handled by Nginx Proxy Manager
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - v2-network
    depends_on:
      - app

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: v2-proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/proxy/data:/data
      - ./docker/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - v2-network

  db:
    container_name: v2-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE:-kericho_v2}
      - POSTGRES_USER=${DB_USERNAME:-kericho}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - v2-db-data:/var/lib/postgresql/data
    networks:
      - v2-network

  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: v2-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - v2-meilisearch-data:/meili_data
    networks:
      - v2-network

networks:
  v2-network:
    driver: bridge

volumes:
  v2-db-data:
  v2-meilisearch-data:

