server {
    listen 80;
    listen [::]:80;
    server_name sklep.kerichogold.com.pl www.sklep.kerichogold.com.pl;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sklep.kerichogold.com.pl www.sklep.kerichogold.com.pl;

    ssl_certificate /etc/letsencrypt/live/sklep.kerichogold.com.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sklep.kerichogold.com.pl/privkey.pem;

    root /var/www/html/public;
    index index.php index.html;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
